### ISSUE TITLE
Knockout Components - Require without Custom Component Loaders

### ISSUE THREAD

**Issue by carlosagsmendes** [knockout/knockout#1712]
Hi,

I would like to use the following - already available syntax - in my components:

```
ko.components.register('my-component', { require: 'some/module' });
```

But I'm using SystemJS (instead of RequireJS).

To make it work I had to change KO source:

```
  function possiblyGetConfigFromAmd(errorCallback, config, callback) {
        if (typeof config['require'] === 'string') {
            // The config is the value of an AMD module
            if (amdRequire || window['require']) {
                System.import(config['require']).then(callback);
              //   //( amdRequire || window['require'])([config['require']], callback);

```
Any chance of making this more pluggable?   

http://stackoverflow.com/questions/28704885/knockout-components-custom-component-loaders?noredirect=1#comment45731283_28704885

**Comment by mbest** [comment]
Possibly related to #1647?

**Comment by carlosagsmendes** [comment]
Hi Michael,

I'm not sure. In my case I found that I can use the 'loadComponent' to use my own loader (System.js):

```
var myComponentLoader = {
  loadComponent: function(name, componentConfig, callback) {
    System.import(componentConfig.myLoader)
    .then(function(loadedComponent) {

      var result = {
        template: ko.utils.parseHtmlFragment(loadedComponent.componentTemplate),
        createViewModel: loadedComponent.MyComponentViewModel
      }
      callback(result);
    })
    // .catch(function(myError){
    //   alert(myError);
    //   callback(null);
    // });
    }
};

// Register it
ko.components.loaders.unshift(myComponentLoader);

ko.components.register('my-component', { myLoader: './app/components/components' });
```
PS - It would be useful to further document how to get an array of DOM nodes from an external template here: http://knockoutjs.com/documentation/component-loaders.html#loadcomponentname-componentconfig-callback 

Here's what I'm doing to get an array of nodes from my loaded template: 

```
ko.utils.parseHtmlFragment(loadedComponent.componentTemplate)
```
I'm almost there but... I'm still having problems with the 'loadComponent':

```
 Potentially unhandled rejection [1] ReferenceError: Unable to process binding "text: function (){return myName }"
Message: myName is not defined
    at text (eval at createBindingsStringEvaluator (unknown source), <anonymous>:3:64)
    at ko.bindingHandlers.text.update (http://localhost:8081/lib/bower/knockout@3.3.0/dist/knockout.js:4261:42)
    at ko.utils.arrayForEach.ko.dependentObservable.disposeWhenNodeIsRemoved (http://localhost:8081/lib/bower/knockout@3.3.0/dist/knockout.js:3004:33)
    at evaluateImmediate (http://localhost:8081/lib/bower/knockout@3.3.0/dist/knockout.js:1737:103)
    at Object.ko.computed.ko.dependentObservable (http://localhost:8081/lib/bower/knockout@3.3.0/dist/knockout.js:1946:9)
    at http://localhost:8081/lib/bower/knockout@3.3.0/dist/knockout.js:3002:28
    at Object.ko.utils.arrayForEach (http://localhost:8081/lib/bower/knockout@3.3.0/dist/knockout.js:151:17)
    at applyBindingsToNodeInternal (http://localhost:8081/lib/bower/knockout@3.3.0/dist/knockout.js:2974:22)
    at applyBindingsToNodeAndDescendantsInternal (http://localhost:8081/lib/bower/knockout@3.3.0/dist/knockout.js:2854:37)
    at applyBindingsToDescendantsInternal (http://localhost:8081/lib/bower/knockout@3.3.0/dist/knockout.js:2836:13)
```

http://stackoverflow.com/questions/28704885/knockout-components-custom-component-loaders

I think this approach is the best when adding custom behavior to component loading. If I can get this to work maybe @kcuzner can give it a try.

**Comment by carlosagsmendes** [comment]
Hi @mbest, I was able to sort this out with some help so I'm closing it.

Here's the link if someone experiences the same difficulties.

http://stackoverflow.com/questions/28704885/knockout-components-custom-component-loaders

Thank you for your support
