### ISSUE TITLE
Failed at the knockout@3.3.0 prepublish script 'grunt'

### ISSUE THREAD

**Issue by effiek9999** [knockout/knockout#1727]
This is what happens when I run 'npm install' per your instructions, and I do have java installed (I read that it's required in previous issues):

> grunt

Running "clean" task

Running "checktrailingspaces:main" (checktrailingspaces)

Running "build:debug" (build) task

Running "build:min" (build) task
Compiling...Warning: write EPIPE Use --force to continue.

Aborted due to warnings.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! knockout@3.3.0 prepublish: `grunt`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the knockout@3.3.0 prepublish script 'grunt'.
npm ERR! This is most likely a problem with the knockout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt
npm ERR! You can get their info via:
npm ERR!     npm owner ls knockout
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\blah blah\npm-debug.
log

Here is my npm-debug.log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'install' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\node.exe
5 verbose install where, deps [ 'C:\Users\effiekazakos\Documents\GitHub\knockout\knockout',
5 verbose install [ 'grunt', 'grunt-cli', 'closure-compiler' ] ]
6 verbose install where, peers [ 'C:\Users\effiekazakos\Documents\GitHub\knockout\knockout',
6 verbose install [] ]
7 info preinstall knockout@3.3.0
8 verbose already installed skipping grunt@~0.4.1 C:\Users\effiekazakos\Documents\GitHub\knockout\knockout
9 verbose already installed skipping grunt-cli@~0.1.0 C:\Users\effiekazakos\Documents\GitHub\knockout\knockout
10 verbose already installed skipping closure-compiler@~0.2.1 C:\Users\effiekazakos\Documents\GitHub\knockout\knockout
11 silly install resolved []
12 info build C:\Users\effiekazakos\Documents\GitHub\knockout\knockout
13 verbose linkStuff [ false,
13 verbose linkStuff false,
13 verbose linkStuff false,
13 verbose linkStuff 'C:\Users\effiekazakos\Documents\GitHub\knockout' ]
14 info linkStuff knockout@3.3.0
15 verbose linkBins knockout@3.3.0
16 verbose linkMans knockout@3.3.0
17 verbose rebuildBundles knockout@3.3.0
18 verbose rebuildBundles [ '.bin', 'closure-compiler', 'grunt', 'grunt-cli' ]
19 info install knockout@3.3.0
20 info postinstall knockout@3.3.0
21 info prepublish knockout@3.3.0
22 verbose unsafe-perm in lifecycle true
23 info knockout@3.3.0 Failed to exec prepublish script
24 verbose stack Error: knockout@3.3.0 prepublish: grunt
24 verbose stack Exit status 3
24 verbose stack at EventEmitter. (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
24 verbose stack at EventEmitter.emit (events.js:110:17)
24 verbose stack at ChildProcess. (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
24 verbose stack at ChildProcess.emit (events.js:110:17)
24 verbose stack at maybeClose (child_process.js:1008:16)
24 verbose stack at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
25 verbose pkgid knockout@3.3.0
26 verbose cwd C:\Users\effiekazakos\Documents\GitHub\knockout\knockout
27 error Windows_NT 6.1.7601
28 error argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
29 error node v0.12.0
30 error npm v2.5.1
31 error code ELIFECYCLE
32 error knockout@3.3.0 prepublish: grunt
32 error Exit status 3
33 error Failed at the knockout@3.3.0 prepublish script 'grunt'.
33 error This is most likely a problem with the knockout package,
33 error not with npm itself.
33 error Tell the author that this fails on your system:
33 error grunt
33 error You can get their info via:
33 error npm owner ls knockout
33 error There is likely additional logging output above.
34 verbose exit [ 1, true ]

**Comment by effiek9999** [comment]
Here is my npm-debug.log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose install where, deps [ 'C:\\Users\\effiekazakos\\Documents\\GitHub\\knockout\\knockout',
5 verbose install   [ 'grunt', 'grunt-cli', 'closure-compiler' ] ]
6 verbose install where, peers [ 'C:\\Users\\effiekazakos\\Documents\\GitHub\\knockout\\knockout',
6 verbose install   [] ]
7 info preinstall knockout@3.3.0
8 verbose already installed skipping grunt@~0.4.1 C:\Users\effiekazakos\Documents\GitHub\knockout\knockout
9 verbose already installed skipping grunt-cli@~0.1.0 C:\Users\effiekazakos\Documents\GitHub\knockout\knockout
10 verbose already installed skipping closure-compiler@~0.2.1 C:\Users\effiekazakos\Documents\GitHub\knockout\knockout
11 silly install resolved []
12 info build C:\Users\effiekazakos\Documents\GitHub\knockout\knockout
13 verbose linkStuff [ false,
13 verbose linkStuff   false,
13 verbose linkStuff   false,
13 verbose linkStuff   'C:\\Users\\effiekazakos\\Documents\\GitHub\\knockout' ]
14 info linkStuff knockout@3.3.0
15 verbose linkBins knockout@3.3.0
16 verbose linkMans knockout@3.3.0
17 verbose rebuildBundles knockout@3.3.0
18 verbose rebuildBundles [ '.bin', 'closure-compiler', 'grunt', 'grunt-cli' ]
19 info install knockout@3.3.0
20 info postinstall knockout@3.3.0
21 info prepublish knockout@3.3.0
22 verbose unsafe-perm in lifecycle true
23 info knockout@3.3.0 Failed to exec prepublish script
24 verbose stack Error: knockout@3.3.0 prepublish: `grunt`
24 verbose stack Exit status 3
24 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
24 verbose stack     at EventEmitter.emit (events.js:110:17)
24 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
24 verbose stack     at ChildProcess.emit (events.js:110:17)
24 verbose stack     at maybeClose (child_process.js:1008:16)
24 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
25 verbose pkgid knockout@3.3.0
26 verbose cwd C:\Users\effiekazakos\Documents\GitHub\knockout\knockout
27 error Windows_NT 6.1.7601
28 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
29 error node v0.12.0
30 error npm  v2.5.1
31 error code ELIFECYCLE
32 error knockout@3.3.0 prepublish: `grunt`
32 error Exit status 3
33 error Failed at the knockout@3.3.0 prepublish script 'grunt'.
33 error This is most likely a problem with the knockout package,
33 error not with npm itself.
33 error Tell the author that this fails on your system:
33 error     grunt
33 error You can get their info via:
33 error     npm owner ls knockout
33 error There is likely additional logging output above.
34 verbose exit [ 1, true ]

**Comment by effiek9999** [comment]
My bad. I didn't have full write permissions and then I reinstalled java and it worked.
